### ISSUE TITLE
Accept parameters in execute methods

### ISSUE THREAD

**Issue by TomAugspurger** [mapd/pymapd#13]
Just need to figure out how to properly quote things.

**Comment by TomAugspurger** [comment]
@andrewseidl in https://github.com/mapd/mapd-core/blob/21fc39fab9e1dc2c1682bcf3dcc2b49d5503aea6/Planner/Planner.h#L243 I see a TODO note for the database to support parametrized queries, do you know if there's been any interest in that in the meantime?

The way this works in python is `Cursor.execute` takes a string with the query and parameters:

```
query = 'select depdelay from flights_2008_10k where depdelay > (%d);'
params = (10,)
cursor.execute(query, params)
```

With the idea being the user doesn't have to do string interpolating themselves, thus avoiding a sql injecting vulnerability.

I have a basic version up in #25. It relies on a third-party library to do the sql escaping.

**Comment by andrewseidl** [comment]
Not currently, we instead have been relying on the driver to implement prepared statements/ parameterized queries and handle the escaping (sorry!).
