### ISSUE TITLE
Make load_table_columnar the default load_table

### ISSUE THREAD

**Issue by tmostak** [mapd/pymapd#52]
If load_table_columnar is roughly 10X faster than load_table (row-wise), and there are no other downsides, it seems it would make sense to make load_table default to load_table_columnar. If there are good reasons we can keep around the row-wise loader as load_table_rowwise or something. Thoughts?

**Comment by TomAugspurger** [comment]
This was implemented as part of https://github.com/mapd/pymapd/pull/53, at least for DataFrames and Arrow tables, see the `method` keyword [here](http://pymapd.readthedocs.io/en/latest/api.html#pymapd.Connection.load_table).

For lists of tuples, we still use the row-wise loader. In theory, we could convert those to DataFrames, but then we'd have to guess column names and dtypes. For now, I think it's Ok to leave those on the slow loader, and have the user convert to a DataFrame or Table if they want the speed.
