### ISSUE TITLE
'Connection' object has no attribute 'load_table_arrow'

### ISSUE THREAD

**Issue by v1nsai** [mapd/pymapd#55]
```
import pyarrow as pa
import pandas as pd
import pymapd as pm
mapd_con = pm.connect(user="mapd", password='password', host="localhost", dbname="mapd")
mapd_cursor = mapd_con.cursor()
df = pd.DataFrame({"A": [1, 2], "B": ['c', 'd']})
table = pa.Table.from_pandas(df)
con.load_table_arrow("test", table)

#error text
'Connection' object has no attribute 'load_table_arrow'
```

Installed pymapd via `conda install -c conda-forge pymapd` but it can't find `load_table_arrow`, `load_table_columnar` and I get a weird error about columns when trying to use `load_table`. 

With so little code being used and no errors on `pm.connect`, seems more likely to be a bug in `pymapd` than something on my end.

**Comment by TomAugspurger** [comment]
Hi @v1nsai. I haven't made a release since #53 was merged. I'll put one up later today.

If you're on linux, you can install the dev-build at conda install -c pymapd/label/dev pymapd. Otherwise you could build from source.

**Comment by TomAugspurger** [comment]
Just merged the PR to the pymapd-feedstock, so the packages should show up in the conda-forge channel over the next few hours.
