### ISSUE TITLE
Incorrect decoding of null value

### ISSUE THREAD

**Issue by dallinregehr** [mapd/pymapd#58]
I have a column encoded as `SMALLINT ENCODING FIXED(8)`. When grouping by that column, all results return as expected except `null` which comes across as the value `-32768`. 

It appears to be an issue with how pymapd parses the Thrift responses because when I execute a the same query through MapD's Immerse tool the results contain `null` as expected.

**Comment by TomAugspurger** [comment]
Thanks for the report, I'm able to replicate it:

```python
In [4]: con = pymapd.connect(user="mapd", dbname="mapd", password="HyperInteractive", host="localhost")
In [5]: con
In [5]: con
Out[5]: Connection(mapd://mapd:***@localhost:9091/mapd?protocol=binary)

In [6]: con.execute("create table tmp (A SMALLINT);");
In [7]: con.execute("insert into tmp VALUES (1);");
In [8]: con.execute("insert into tmp VALUES (null);");
In [10]: con.execute("select * from tmp").fetchall()
Out[10]: [(1,), (-32768,)]
```

I'll have a fix later today.

**Comment by dallinregehr** [comment]
Thanks for the fast response and fix!

**Comment by dallinregehr** [comment]
Do you have an ETA for another official release?

**Comment by TomAugspurger** [comment]
Soon :) I hoped to on Friday but got busy with other things.

Master is in a good state, so I can do one tomorrow I think.

**Comment by TomAugspurger** [comment]
I just merged the conda-forge PR, so conda packages should be built in a
few hours.

**Comment by dallinregehr** [comment]
Great! Will it also be available using `pip`?

**Comment by TomAugspurger** [comment]
Yes, it's already up on PyPI at https://pypi.org/project/pymapd/. You'll
need a C compiler to build the extensions though.

Tom
